# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-02 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LlaveValor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('llave', models.CharField(max_length=100)),
                ('valor', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'llave_valor',
            },
        ),
    ]
